### ISSUE TITLE
Do not save to "/tmp"

### ISSUE THREAD

**Issue by 0312birdzhang** [perqin/shadowsocksq-linux#2]
https://github.com/perqin/shadowsocksq-linux/blob/67acbb3232a79e4aa0f2712b2d10ef306a90749c/internal/app/ssq/sqlite/sqlite.go#L11

It will be deleted after reboot on some Linux distribution.

`/home/username/[.cache|.conf]/` or `/home/username/.shadowsocksq-linux/` is much better

**Comment by perqin** [comment]
This project is currently archived. [perqin/shadow-dashboard](https://github.com/perqin/shadow-dashboard) is the ancestor of this project.
